services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings

  flower:
    image: mher/flower
    depends_on:
      - redis
      - celery
    ports:
      - 5000:5555

    environment:
      CELERY_BROKER_URL: redis://redis:6379/${REDIS_DB}

volumes:
  postgres_data:
  redis_data:
